INSERT INTO public.user(id, name) VALUES (1, 'Guigui');
INSERT INTO public.user(id, name) VALUES (2, 'Alex');
INSERT INTO public.user(id, name) VALUES (3, 'Zak');
INSERT INTO public.user(id, name) VALUES (4, 'Udev');
INSERT INTO public.user(id, name) VALUES (5, 'Oz');
INSERT INTO public.user(id, name) VALUES (6, 'Lou');
INSERT INTO public.user(id, name) VALUES (7, 'Jerem');
INSERT INTO public.user(id, name) VALUES (8, 'Pikachu');

INSERT INTO public.article(id, title, image, message, author) VALUES (1, 'Nouveauté sur Spring boot', '7', 'Des nouveautés sur spring ca ira plus vite encore. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis in arcu efficitur vehicula. Duis ut diam tristique dui aliquet tincidunt quis ac lacus. Donec consequat vitae purus non vehicula. Nulla tempor lacus a tortor varius, eget mattis massa ornare. Nulla facilisi. Maecenas blandit varius tincidunt. Donec semper at mauris vel imperdiet. Vivamus dignissim nisi vel facilisis luctus.

In cursus nec libero vel tincidunt. Ut mattis et sapien ullamcorper hendrerit. Vivamus malesuada orci placerat gravida placerat. Curabitur tristique enim sed sapien porttitor, eu volutpat enim rhoncus. Sed in lacinia sem. Quisque et aliquet enim, id tempor erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eleifend enim erat, vel finibus lorem tincidunt eget. Vivamus interdum justo a massa pulvinar, et ultrices justo vehicula. Aenean id efficitur lorem. Integer porttitor dignissim auctor. Nulla accumsan augue a sapien vestibulum fringilla. In commodo imperdiet augue, vel bibendum nunc luctus eu. Integer vitae tristique mauris.', 1);
INSERT INTO public.article(id, title, image, message, author) VALUES (2, 'Fitness Park', '4', 'Présentation du projet en salle de sport. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis in arcu efficitur vehicula. Duis ut diam tristique dui aliquet tincidunt quis ac lacus. Donec consequat vitae purus non vehicula. Nulla tempor lacus a tortor varius, eget mattis massa ornare. Nulla facilisi. Maecenas blandit varius tincidunt. Donec semper at mauris vel imperdiet. Vivamus dignissim nisi vel facilisis luctus.

In cursus nec libero vel tincidunt. Ut mattis et sapien ullamcorper hendrerit. Vivamus malesuada orci placerat gravida placerat. Curabitur tristique enim sed sapien porttitor, eu volutpat enim rhoncus. Sed in lacinia sem. Quisque et aliquet enim, id tempor erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eleifend enim erat, vel finibus lorem tincidunt eget. Vivamus interdum justo a massa pulvinar, et ultrices justo vehicula. Aenean id efficitur lorem. Integer porttitor dignissim auctor. Nulla accumsan augue a sapien vestibulum fringilla. In commodo imperdiet augue, vel bibendum nunc luctus eu. Integer vitae tristique mauris.', 2);
INSERT INTO public.article(id, title, image, message, author) VALUES (3, 'Angular vs React', '3', 'Que le combat commence. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis in arcu efficitur vehicula. Duis ut diam tristique dui aliquet tincidunt quis ac lacus. Donec consequat vitae purus non vehicula. Nulla tempor lacus a tortor varius, eget mattis massa ornare. Nulla facilisi. Maecenas blandit varius tincidunt. Donec semper at mauris vel imperdiet. Vivamus dignissim nisi vel facilisis luctus.

In cursus nec libero vel tincidunt. Ut mattis et sapien ullamcorper hendrerit. Vivamus malesuada orci placerat gravida placerat. Curabitur tristique enim sed sapien porttitor, eu volutpat enim rhoncus. Sed in lacinia sem. Quisque et aliquet enim, id tempor erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eleifend enim erat, vel finibus lorem tincidunt eget. Vivamus interdum justo a massa pulvinar, et ultrices justo vehicula. Aenean id efficitur lorem. Integer porttitor dignissim auctor. Nulla accumsan augue a sapien vestibulum fringilla. In commodo imperdiet augue, vel bibendum nunc luctus eu. Integer vitae tristique mauris.', 3);
INSERT INTO public.article(id, title, image, message, author) VALUES (4, 'Avez vous tout compris ??? ', '2', 'Je comprends pas vraiment tout tout. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis in arcu efficitur vehicula. Duis ut diam tristique dui aliquet tincidunt quis ac lacus. Donec consequat vitae purus non vehicula. Nulla tempor lacus a tortor varius, eget mattis massa ornare. Nulla facilisi. Maecenas blandit varius tincidunt. Donec semper at mauris vel imperdiet. Vivamus dignissim nisi vel facilisis luctus.

In cursus nec libero vel tincidunt. Ut mattis et sapien ullamcorper hendrerit. Vivamus malesuada orci placerat gravida placerat. Curabitur tristique enim sed sapien porttitor, eu volutpat enim rhoncus. Sed in lacinia sem. Quisque et aliquet enim, id tempor erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eleifend enim erat, vel finibus lorem tincidunt eget. Vivamus interdum justo a massa pulvinar, et ultrices justo vehicula. Aenean id efficitur lorem. Integer porttitor dignissim auctor. Nulla accumsan augue a sapien vestibulum fringilla. In commodo imperdiet augue, vel bibendum nunc luctus eu. Integer vitae tristique mauris.', 4);
INSERT INTO public.article(id, title, image, message, author) VALUES (5, 'Rebelle ? Et alors ?', '5', 'Je ne remplirais pas ma feuille de satisfaction de module. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis in arcu efficitur vehicula. Duis ut diam tristique dui aliquet tincidunt quis ac lacus. Donec consequat vitae purus non vehicula. Nulla tempor lacus a tortor varius, eget mattis massa ornare. Nulla facilisi. Maecenas blandit varius tincidunt. Donec semper at mauris vel imperdiet. Vivamus dignissim nisi vel facilisis luctus.

In cursus nec libero vel tincidunt. Ut mattis et sapien ullamcorper hendrerit. Vivamus malesuada orci placerat gravida placerat. Curabitur tristique enim sed sapien porttitor, eu volutpat enim rhoncus. Sed in lacinia sem. Quisque et aliquet enim, id tempor erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eleifend enim erat, vel finibus lorem tincidunt eget. Vivamus interdum justo a massa pulvinar, et ultrices justo vehicula. Aenean id efficitur lorem. Integer porttitor dignissim auctor. Nulla accumsan augue a sapien vestibulum fringilla. In commodo imperdiet augue, vel bibendum nunc luctus eu. Integer vitae tristique mauris.', 5);
INSERT INTO public.article(id, title, image, message, author) VALUES (6, 'Big Boss bientôt', '6', 'Je voudrais passer VP voir plus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis in arcu efficitur vehicula. Duis ut diam tristique dui aliquet tincidunt quis ac lacus. Donec consequat vitae purus non vehicula. Nulla tempor lacus a tortor varius, eget mattis massa ornare. Nulla facilisi. Maecenas blandit varius tincidunt. Donec semper at mauris vel imperdiet. Vivamus dignissim nisi vel facilisis luctus.

In cursus nec libero vel tincidunt. Ut mattis et sapien ullamcorper hendrerit. Vivamus malesuada orci placerat gravida placerat. Curabitur tristique enim sed sapien porttitor, eu volutpat enim rhoncus. Sed in lacinia sem. Quisque et aliquet enim, id tempor erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eleifend enim erat, vel finibus lorem tincidunt eget. Vivamus interdum justo a massa pulvinar, et ultrices justo vehicula. Aenean id efficitur lorem. Integer porttitor dignissim auctor. Nulla accumsan augue a sapien vestibulum fringilla. In commodo imperdiet augue, vel bibendum nunc luctus eu. Integer vitae tristique mauris.', 6);
INSERT INTO public.article(id, title, image, message, author) VALUES (7, 'Mes lunettes ?', '1', 'Je dois faire le front mais où sont mes lunettes, je ne les trouve plus', 7);
INSERT INTO public.article(id, title, image, message, author) VALUES (8, 'Pika ?', '8', 'Pika pika pika pikachu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis in arcu efficitur vehicula. Duis ut diam tristique dui aliquet tincidunt quis ac lacus. Donec consequat vitae purus non vehicula. Nulla tempor lacus a tortor varius, eget mattis massa ornare. Nulla facilisi. Maecenas blandit varius tincidunt. Donec semper at mauris vel imperdiet. Vivamus dignissim nisi vel facilisis luctus.

In cursus nec libero vel tincidunt. Ut mattis et sapien ullamcorper hendrerit. Vivamus malesuada orci placerat gravida placerat. Curabitur tristique enim sed sapien porttitor, eu volutpat enim rhoncus. Sed in lacinia sem. Quisque et aliquet enim, id tempor erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eleifend enim erat, vel finibus lorem tincidunt eget. Vivamus interdum justo a massa pulvinar, et ultrices justo vehicula. Aenean id efficitur lorem. Integer porttitor dignissim auctor. Nulla accumsan augue a sapien vestibulum fringilla. In commodo imperdiet augue, vel bibendum nunc luctus eu. Integer vitae tristique mauris.', 8);

INSERT INTO public.comment(id, message, author, article) VALUES (1, 'Comment 1', 1, 1);
INSERT INTO public.comment(id, message, author, article) VALUES (2, 'Comment 2', 2, 1);
INSERT INTO public.comment(id, message, author, article) VALUES (3, 'Comment 3', 1, 2);
